version: '3.8'

services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    env_file:
      - ../.env
    environment:
      - DBNAME=crm
      - DBUSER=crm
      - DBPASSWORD=crm
      - DBHOST=crm-db
      - DBPORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - crm-db
      - redis
    ports:
      - 8000:8000
    networks:
      - nw

  crm-db:
    image: postgres:latest
    container_name: crm-db
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - nw
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      retries: 5
      start_period: 5s

  celery:
    image: djcrm:1
    container_name: crm-celery
    command: celery -A crm worker -l info
    depends_on:
      - crm-app
      - redis
    env_file:
      - ../.env
    environment:
      - DBNAME=crm
      - DBUSER=crm
      - DBPASSWORD=crm
      - DBHOST=crm-db
      - DBPORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - nw
    
networks:
  nw: {}

volumes:
  postgres_data: {}
